# Headless service providing a network domain for the stateful set
apiVersion: v1
kind: Service
metadata:
  name: esgf-zk
  labels:
    stack: esgf
    component: zookeeper
spec:
  ports:
    - name: follower
      port: 2888
    - name: leader-election
      port: 3888
  clusterIP: None
  selector:
    stack: esgf
    component: zookeeper
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: esgf-zk
  labels:
    stack: esgf
    component: zookeeper
spec:
  selector:
    matchLabels:
      stack: esgf
      component: zookeeper
  # This is the service for the network domain
  serviceName: esgf-zk
  # Currently, this cannot be scaled dynamically. It must be odd and >= 3 for quorum to be maintained
  replicas: 1
  template:
    metadata:
      labels:
        stack: esgf
        component: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:latest
          #imagePullPolicy: {{ default "" .Values.zookeeper.imagePullPolicy | quote }}
          ports:
            - name: client
              containerPort: 2181
            - name: follower
              containerPort: 2888
            - name: leader-election
              containerPort: 3888
          volumeMounts:
            - name: zk-data
              mountPath: /data
            - name: zk-datalog
              mountPath: /datalog
          env:
            - name: ZOO_REPLICAS
              value: "1"
            - name: ZOO_INIT_LIMIT
              value: "10"
            - name: ZOO_SYNC_LIMIT
              value: "5"
          # Currently, the statefulset ordinal is not available independently
          # of the hostname, so we need to rip it out
          # We also build the server list using 0.0.0.0 as the address of the current
          # server to avoid port binding errors due to the DNS entry not being ready
          command:
            - "/bin/sh"
            - "-c"
            - |
              set -e
              # We only need to do this stuff if we are running clustered, i.e. replicas > 1
              if [ "$ZOO_REPLICAS" -gt "1" ]; then
                export ZOO_MY_ID="${HOSTNAME##*-}"
                ZOO_SERVERS=""
                for i in $(seq 0 $(($ZOO_REPLICAS - 1))); do
                  if [[ "$i" = "$ZOO_MY_ID" ]]; then
                    ZOO_SERVERS="$ZOO_SERVERS server.$i=0.0.0.0:2888:3888"
                  else
                    ZOO_SERVERS="$ZOO_SERVERS server.$i={{ .Release.Name }}-zk-$i.{{ .Release.Name }}-zk:2888:3888"
                  fi
                done
                export ZOO_SERVERS
              fi
              env
              exec /docker-entrypoint.sh zkServer.sh start-foreground
          # For liveness, check that the node is running using the ruok 4 letter word
          #livenessProbe:
          #  exec:
          #    command:
          #      - "/bin/sh"
          #      - "-c"
          #      - "echo ruok | nc 127.0.0.1 2181 | grep imok"
          #  initialDelaySeconds: 10
          #  periodSeconds: 10
          #resources:
#{{ toYaml .Values.zookeeper.resources | indent 12 }}
      volumes:
        - name: zk-data
          emptyDir: {}
        - name: zk-datalog
          emptyDir: {}
