apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esgf-auth
  labels:
    stack: esgf
    component: auth
    auth-role: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      stack: esgf
      component: auth
      auth-role: frontend
  template:
    metadata:
      labels:
        stack: esgf
        component: auth
        auth-role: frontend
    spec:
      initContainers:
        # Wait for postgres to become available before starting
        - name: wait-for-postgres-auth
          image: postgres
          env:
            - name: PGHOST
              value: esgf-postgres-auth
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: authuser
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: esgf-auth-secrets
                  key: auth-database-password
            - name: PGDATABASE
              value: auth
          command:
            # Try every 5 seconds for no longer than 10 mins
            - bash
            - -c
            - |
              for i in $(seq 120); do
                sleep 5
                echo "Attempt $i of 120"
                if pg_isready; then exit 0; fi
              done
              exit 1
      containers:
        - name: auth
          image: esgfhub/auth:latest
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: ESGF_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: esgf-config
                  key: esgf-hostname
            - name: ESGF_DATABASE_HOST
              value: esgf-postgres-esgcet
            # ESGF-Auth settings
            - name: SCRIPT_NAME
              value: /esgf-auth
            - name: ESGF_AUTH_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: esgf-auth-secrets
                  key: auth-secret-key
            - name: ESGF_COOKIE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: esgf-auth-secrets
                  key: shared-cookie-secret-key
            # Database settings
            - name: DJANGO_DATABASE_DEFAULT_ENGINE
              value: django.db.backends.postgresql
            - name: DJANGO_DATABASE_DEFAULT_NAME
              value: auth
            - name: DJANGO_DATABASE_DEFAULT_HOST
              value: esgf-postgres-auth
            - name: DJANGO_DATABASE_DEFAULT_PORT
              value: "5432"
            - name: DJANGO_DATABASE_DEFAULT_USER
              value: authuser
            - name: DJANGO_DATABASE_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esgf-auth-secrets
                  key: auth-database-password
          volumeMounts:
            - mountPath: /esg/certificates/esg-trust-bundle.pem
              name: trust-bundle
              subPath: esg-trust-bundle.pem
      volumes: 
        - name: trust-bundle
          configMap:
            name: esgf-trust-bundle
