apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esgf-postgres-auth
  labels:
    stack: esgf
    component: auth
    auth-role: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      stack: esgf
      component: auth
      auth-role: backend
  template:
    metadata:
      labels:
        stack: esgf
        component: auth
        auth-role: backend
    spec:
      containers:
        - name: auth-postgres
          image: esgfhub/postgres
          ports:
            - name: postgres
              containerPort: 5432
          readinessProbe:
            tcpSocket: &probe
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket: *probe
            initialDelaySeconds: 60
            periodSeconds: 10
          env:
            - name: POSTGRESQL_USER
              value: authuser
            - name: POSTGRESQL_DATABASE
              value: auth
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esgf-auth-secrets
                  key: auth-database-password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: postgres-data
          emptyDir: {}