apiVersion: v1
kind: Secret
metadata:
  name: esgf-auth-secrets
  labels:
    stack: esgf
    component: auth
data:
  auth-database-password: Y2hhbmdlaXQ=
  auth-secret-key: Y2hhbmdlaXQ=
  shared-cookie-secret-key: Y2hhbmdlaXQ=