apiVersion: v1
kind: Service
metadata:
  name: esgf-auth
  labels:
    stack: esgf
    component: auth
    auth-role: frontend
spec:
  ports:
    - name: http
      port: 8000
  selector:
    stack: esgf
    component: auth
    auth-role: frontend
