apiVersion: v1
kind: Service
metadata:
  name: esgf-auth
  labels:
    stack: esgf
    component: auth
spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
  selector:
    stack: esgf
    component: auth
