apiVersion: v1
kind: Service
metadata:
  name: esgf-auth-postgres
  labels:
    stack: esgf
    component: auth-postgres
spec:
  ports:
    - name: postgres
      port: 5432
  selector:
    stack: esgf
    component: auth-postgres
