apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esgf-proxy
  labels:
    stack: esgf
    component: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      stack: esgf
      component: proxy
  template:
    metadata:
      labels:
        stack: esgf
        component: proxy
      #annotations:
      #  checksum/hostcert: {{ include (print $.Template.BasePath "/certificates/hostcert-secret.yaml") . | sha256sum }}
      #  checksum/trust-bundle: {{ include (print $.Template.BasePath "/certificates/trust-bundle-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: proxy
          image: cedadev/esgf-proxy:latest
          #imagePullPolicy: {{ default "" .Values.proxy.imagePullPolicy | quote }}
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
#          livenessProbe:
#            httpGet:
#              path: /esgf-slcs
#              port: 8000
              # The ALLOWED_HOSTS setting means that the app will only accept
              # requests from the correct host
#              httpHeaders:
#                - name: Host
#                  value: "{{ .Values.hostname }}"
#                - name: X-Forwarded-Host
#                  value: "{{ .Values.hostname }}"
#                - name: X-Forwarded-Proto
#                  value: https
#            initialDelaySeconds: 10
#            periodSeconds: 10
          env:
            - name: ESGF_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: esgf-config
                  key: esgf-hostname
            - name: ESGF_SOLR_UPSTREAM
              value: "http://esgf-solr.default.svc.cluster.local:8983"
            - name: ESGF_INDEX_NODE_UPSTREAM
              value: "http://esgf-index-node.default.svc.cluster.local:8080"
            - name: ESGF_TDS_UPSTREAM
              value: "http://esgf-tds.default.svc.cluster.local:8080"
            - name: ESGF_COG_UPSTREAM
              value: "http://esgf-cog.default.svc.cluster.local:8000"
            - name: ESGF_ORP_UPSTREAM
              value: "http://esgf-orp.default.svc.cluster.local:8080"
            - name: ESGF_IDP_UPSTREAM
              value: "http://esgf-idp-node.default.svc.cluster.local:8080"
            - name: ESGF_SLCS_UPSTREAM
              value: "http://esgf-slcs.default.svc.cluster.local:8000"
            - name: ESGF_AUTH_UPSTREAM
              value: "http://esgf-auth.default.svc.cluster.local:8000"
          volumeMounts:
            - mountPath: /etc/nginx/ssl/hostcert.crt
              name: hostcert
              subPath: tls.crt
            - mountPath: /etc/nginx/ssl/hostcert.key
              name: hostcert
              subPath: tls.key
            - mountPath: /esg/certificates/esg-trust-bundle.pem
              name: trust-bundle
              subPath: esg-trust-bundle.pem
          #resources:
#{{ toYaml .Values.proxy.resources | indent 12 }}
      volumes:
        - name: hostcert
          secret:
            secretName: esgf-hostcert
        - name: trust-bundle
          configMap:
            name: esgf-trust-bundle
        - name: esgf-config
          configMap:
            name: esgf-config