apiVersion: v1
kind: Service
metadata:
  name: esgf-proxy
  labels:
    stack: esgf
    component: proxy
spec:
  type: NodePort
  ports:
    - name: https
      port: 443
  selector:
    stack: esgf
    component: proxy
