apiVersion: v1
kind: Service
metadata:
  name: esgf-proxy
  labels:
    stack: esgf
    component: proxy
spec:
  ports:
    - name: https
      port: 443
  #externalIPs:
  #  - 192.168.64.12
  #type: NodePort
  selector:
    stack: esgf
    component: proxy