apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esgf-cog
  labels:
    stack: esgf
    component: cog
    cog-role: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      stack: esgf
      component: cog
  template:
    metadata:
      labels:
        stack: esgf
        component: cog
    spec:
      initContainers:
        # Wait for postgres to become available before starting
        - name: wait-for-postgres
          image: postgres
          env:
            - name: PGHOST
              value: esgf-postgres-esgcet
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: dbsuper
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: esgf-postgres-esgcet-secrets
                  key: database-password
            - name: PGDATABASE
              value: esgcet
          command:
            # Try every 5 seconds for no longer than 10 mins
            - bash
            - -c
            - |
              for i in $(seq 120); do
                sleep 5
                echo "Attempt $i of 120"
                if pg_isready; then exit 0; fi
              done
              exit 1
        - name: wait-for-postgres-cog
          image: postgres
          env:
            - name: PGHOST
              value: esgf-postgres-cog
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: dbsuper
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: esgf-postgres-esgcet-secrets
                  key: database-password
            - name: PGDATABASE
              value: cogdb
          command:
            # Try every 5 seconds for no longer than 10 mins
            - bash
            - -c
            - |
              for i in $(seq 120); do
                sleep 5
                echo "Attempt $i of 120"
                if pg_isready; then exit 0; fi
              done
              exit 1
      containers:
        - name: cog
          image: esgfhub/cog:latest
          #command: ["tail", "-f", "/dev/null"]
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: ESGF_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: esgf-config
                  key: esgf-hostname
            - name: ESGF_DATABASE_HOST
              value: esgf-postgres-esgcet
            - name: ESGF_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esgf-postgres-esgcet-secrets
                  key: database-password
            - name: ESGF_ROOTADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esgf-cog-secrets
                  key: rootadmin-password
            - name: ESGF_COG_TIME_ZONE
              value: "America/Denver"
            - name: ESGF_COG_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: esgf-cog-secrets
                  key: cog-secret-key
            - name: ESGF_COG_DATABASE_HOST
              value: esgf-postgres-cog
            - name: ESGF_COG_DATABASE_PORT
              value: "5432"
            - name: ESGF_COG_DATABASE_NAME
              value: cogdb
            - name: ESGF_COG_DATABASE_USER
              value: dbsuper
            - name: ESGF_COG_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esgf-postgres-esgcet-secrets
                  key: database-password
          volumeMounts:
            - mountPath: /esg/certificates/esg-trust-bundle.pem
              name: trust-bundle
              subPath: esg-trust-bundle.pem
      volumes:
        - name: trust-bundle
          configMap:
            name: esgf-trust-bundle
