apiVersion: v1
kind: Service
metadata:
  name: esgf-postgres-cog
  labels:
    stack: esgf
    component: cog
    cog-role: backend
spec:
  ports:
    - name: postgres
      port: 5432
  selector:
    stack: esgf
    component: cog
    cog-role: backend
