apiVersion: v1
kind: Service
metadata:
  name: esgf-tds
  labels:
    stack: esgf
    component: tds
spec:
  #type: NodePort
  ports:
    - name: http
      port: 8080
  selector:
    stack: esgf
    component: tds
