apiVersion: v1
kind: Service
metadata:
  name: esgf-solr-master
  labels:
    stack: esgf
    component: solr
    solr-role: master
spec:
  ports:
    - name: solr
      port: 8983
  selector:
    stack: esgf
    component: solr
    solr-role: master
