apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr-home-master
  labels:
    stack: esgf
    component: solr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solr-home-slave
  labels:
    stack: esgf
    component: solr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
