apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esgf-orp
  labels:
    stack: esgf
    component: orp
spec:
  replicas: 1
  selector:
    matchLabels:
      stack: esgf
      component: orp
  template:
    metadata:
      labels:
        stack: esgf
        component: orp
    spec:
      containers:
        - name: orp
          image: esgfhub/orp:latest
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ESGF_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: esgf-config
                  key: esgf-hostname
            - name: ESGF_DATABASE_HOST
              value: esgf-postgres
            - name: ESGF_SAML_CERT_FILE
              value: /esg/certificates/hostcert/hostcert.crt
            - name: ESGF_SAML_KEY_FILE
              value: /esg/certificates/hostcert/hostcert.key
          volumeMounts:
            - mountPath: /esg/certificates/hostcert/hostcert.crt
              name: hostcert
              subPath: tls.crt
            - mountPath: /esg/certificates/hostcert/hostcert.key
              name: hostcert
              subPath: tls.key
            - mountPath: /esg/certificates/esg-trust-bundle.pem
              name: trust-bundle
              subPath: esg-trust-bundle.pem
      volumes:
        - name: hostcert
          secret:
            secretName: esgf-hostcert
        - name: trust-bundle
          configMap:
            name: esgf-trust-bundle