apiVersion: v1
kind: Service
metadata:
  name: esgf-orp
  labels:
    stack: esgf
    component: orp
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
  selector:
    stack: esgf
    component: orp
