apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esgf-index-node
  labels:
    stack: esgf
    component: index-node
spec:
  replicas: 1
  selector:
    matchLabels:
      stack: esgf
      component: index-node
  template:
    metadata:
      labels:
        stack: esgf
        component: index-node
    spec:
      initContainers:
        - name: wait-for-solr-slave
          image: esgfhub/solr:latest
          args:
            - "wait-for-solr.sh"
            - "--max-attempts"
            - "120"
            - "--solr-url"
            - "http://esgf-solr-slave:8983"
      containers:
        - name: index-node
          # FIXME: this images fixes the localhost:8983 problem
          #image: esgfhublc/index-node:devel2
          image: esgfhub/index-node:latest
          ports:
            - name: http
              containerPort: 8080
          #readinessProbe:
          #  httpGet: &probe
          #    path: /esg-search/search
          #    port: 8080
          #  initialDelaySeconds: 10
          #  periodSeconds: 10
          #livenessProbe:
          #  httpGet: *probe
          #  initialDelaySeconds: 60
          #  periodSeconds: 10
          env:
            - name: ESGF_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: esgf-config
                  key: esgf-hostname
            - name: ESGF_DATABASE_HOST
              value: esgf-postgres
            - name: ESGF_SOLR_HOSTNAME
              value: esgf-solr:8983
            - name: ESGF_SOLR_QUERY_URL
              value: "http://esgf-solr-slave:8983"
            - name: ESGF_SOLR_PUBLISH_URL
              value: "http://esgf-solr-master:8983"              
          volumeMounts:
            - mountPath: /esg/certificates/esg-trust-bundle.pem
              name: trust-bundle
              subPath: esg-trust-bundle.pem
      volumes:
        - name: trust-bundle
          configMap:
            name: esgf-trust-bundle