apiVersion: v1
kind: Service
metadata:
  name: esgf-index-node
  labels:
    stack: esgf
    component: index-node
spec:
  ports:
    - name: http
      port: 8080
  selector:
    stack: esgf
    component: index-node
