apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    stack: esgf
    component: postgres
spec:
  ports:
    - name: postgres
      port: 5432
  selector:
    stack: esgf
    component: postgres
