apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esgf-slcs-postgres
  labels:
    stack: esgf
    component: slcs-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      stack: esgf
      component: slcs-postgres
  template:
    metadata:
      labels:
        stack: esgf
        component: slcs-postgres
      #annotations:
      #  checksum/slcs-secrets: {{ include (print $.Template.BasePath "/slcs/secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: slcs-postgres
          image: postgres:10
          #imagePullPolicy: {{ default "" .Values.slcs.postgres.imagePullPolicy | quote }}
          ports:
            - name: postgres
              containerPort: 5432
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: POSTGRES_USER
              value: slcsuser
            - name: POSTGRES_DB
              value: slcs
            - name: POSTGRES_INITDB_ARGS
              value: "--encoding=UTF-8"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esgf-slcs-secrets
                  key: "slcs-database-password"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
