apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: esgf-postgres-slcs
  labels:
    stack: esgf
    component: slcs
    slcs-role: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      stack: esgf
      component: slcs
      slcs-role: backend
  template:
    metadata:
      labels:
        stack: esgf
        component: slcs
        slcs-role: backend
    spec: 
      containers:
        - name: postgres-slcs
          image: esgfhub/postgres:latest
          ports:
            - name: postgres
              containerPort: 5432
          readinessProbe:
            tcpSocket: &probe
              port: 5432
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket: *probe
            initialDelaySeconds: 60
            periodSeconds: 10
          env:
            - name: POSTGRESQL_DATABASE
              value: slcs
            - name: POSTGRESQL_USER
              value: slcsuser
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: esgf-slcs-secrets
                  key: slcs-database-password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: postgres-data
          emptyDir: {}
