apiVersion: v1
kind: Service
metadata:
  name: esgf-slcs
  labels:
    stack: esgf
    component: slcs
    slcs-role: frontend
spec:
  ports:
    - name: http
      port: 8000
  selector:
    stack: esgf
    component: slcs
    slcs-role: frontend
