apiVersion: v1
kind: Service
metadata:
  name: esgf-postgres-slcs
  labels:
    stack: esgf
    component: slcs
    slcs-role: backend
spec:
  ports:
    - name: postgres
      port: 5432
  selector:
    stack: esgf
    component: slcs
    slcs-role: backend
