apiVersion: v1
kind: Service
metadata:
  name: esgf-postgres-esgcet
  labels:
    stack: esgf
    component: postgres-esgcet
spec:
  ports:
    - name: postgres
      port: 5432
  selector:
    stack: esgf
    component: postgres-esgcet
