apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-esgcet-data
  labels:
    stack: esgf
    component: postgres-esgcet
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
