apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: idp-node-deployment
  labels:
    stack: esgf
    component: idp-node
spec:
  replicas: 1
  selector:
    matchLabels:
      stack: esgf
      component: idp-node
  template:
    metadata:
      labels:
        stack: esgf
        component: idp-node
    spec:
      containers:
        - name: idp-node
          image: cedadev/esgf-idp-node:latest
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ESGF_HOSTNAME
              value: my-node.esgf.org
            - name: ESGF_DATABASE_HOST
              value: postgres-service
            - name: ESGF_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: database-password
          volumeMounts:
            - mountPath: /esg/certificates/esg-trust-bundle.pem
              name: trust-bundle
              subPath: esg-trust-bundle.pem
          resources:
      volumes:
        - name: trust-bundle
          configMap:
            name: trust-bundle-config
