apiVersion: v1
kind: Service
metadata:
  name: esgf-idp-node
  labels:
    stack: esgf
    component: idp-node
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
  selector:
    stack: esgf
    component: idp-node
